const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { JSDOM } = require('jsdom');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'bottega-stack-'));
const src = path.join(__dirname, '../src');
for (const name of ['vercel', 'stack-clienti', 'clienti', 'ponte-stanze']) {
 require('esbuild').buildSync({ entryPoints:[path.join(src, name+'.ts')], outfile:path.join(tmp,name+'.cjs'), bundle:true, platform:'node', external:['vscode'], logLevel:'silent' });
}
const V = require(path.join(tmp,'vercel.cjs'));
const S = require(path.join(tmp,'stack-clienti.cjs'));
const C = require(path.join(tmp,'clienti.cjs'));
const repoDir = path.join(tmp,'app');
fs.mkdirSync(path.join(repoDir,'.git'),{recursive:true});
fs.writeFileSync(path.join(repoDir,'.git/config'),'[remote "origin"]\nurl = git@github.com:example/app.git\n');
const local = {name:'App',path:repoDir};
const raw = {id:'prj_app',name:'app',accountId:'team_test',env:[{value:'NEVER_CACHE'}],link:{type:'github',org:'example',repo:'app',productionBranch:'main',gitCredentialId:'NEVER_CACHE'},targets:{production:{id:'dpl_1',state:'READY',createdAt:1,alias:['example.test']} }};
const project = V.leggiProgetto(raw,[local],[]);
assert.deepEqual(project.localPaths,[repoDir]);
assert.equal(project.repo,'example/app');
assert.equal(project.domain,'example.test');
assert.equal(JSON.stringify(project).includes('NEVER_CACHE'),false);
assert.equal(V.leggiProgetto({id:'bad'},[],[]),undefined);
const github = {at:1,repos:[{repo:'example/app',branch:'main',pushedAt:1,private:true,archived:false},{repo:'example/remote',branch:'main',pushedAt:1,private:true,archived:false}]};
const cfg = {version:1,rounding:15,clients:[{id:'c',nome:'Cliente',progetti:['vercel:prj_app']}]};
const stack = S.buildStack([local],cfg.clients,{catalog:[project],catalogAt:2},github);
assert.equal(stack.assets[0].clientId,'c');
assert.ok(stack.assets.some(a=>a.id==='github:example/remote'));
const start = new Date(2026,9,5,10).getTime();
const ledger = new Map([[repoDir,{name:'App',spans:[start,start+3600000]}]]);
const report = C.buildReport(ledger,cfg,[local],'2026-10',start,{vercel:{catalog:[project]},github});
assert.equal(report.clients[0].minutes,60,'assegnare Vercel assegna anche le ore della cartella esatta');
const conflict = {...cfg,clients:[...cfg.clients,{id:'d',nome:'Altro',progetti:[repoDir]}]};
const conflicted = C.buildReport(ledger,conflict,[local],'2026-10',start,{vercel:{catalog:[project]},github});
assert.equal(conflicted.stack.assets[0].conflict,true);
assert.equal(conflicted.clients.reduce((s,c)=>s+c.minutes,0),0,'nessuna doppia fatturazione con identità in conflitto');
assert.equal(conflicted.unassigned[0].minutes,60);
fs.writeFileSync(path.join(repoDir,'.git/config'),'[remote "upstream"]\nurl = git@github.com:example/wrong.git\n');
assert.equal(V.repoGithub(repoDir),undefined,'solo origin, mai il primo remoto casuale');
fs.writeFileSync(path.join(repoDir,'.git/config'),'[remote "origin"]\nurl = https://evilgithub.com/example/wrong.git\n');
assert.equal(V.repoGithub(repoDir),undefined);
fs.writeFileSync(path.join(repoDir,'.git/config'),'[remote "origin"]\nurl = https://github.com/example/app.git\n');
(async()=>{
 let now=100000000, fail=false, calls=0;
 const gh = new S.GithubInventory(path.join(tmp,'github.json'),async page=>{
  calls++; if(fail) throw new Error('SECRET');
  return page===1?Array.from({length:100},(_,i)=>({full_name:`example/repo${i}`,default_branch:'main',pushed_at:'2026-10-01T00:00:00Z',token:'NEVER_CACHE'})):[];
 },()=>now);
 assert.equal((await gh.refresh()).repos.length,100);
 assert.equal(calls,2,'paginazione GitHub');
 assert.equal(fs.statSync(path.join(tmp,'github.json')).mode&0o777,0o600);
 assert.equal(fs.readFileSync(path.join(tmp,'github.json'),'utf8').includes('NEVER_CACHE'),false);
 await gh.refresh(); assert.equal(calls,2,'cache evita richieste duplicate');
 now+=900001;fail=true;
 const old=await gh.refresh();assert.equal(old.repos.length,100);assert.ok(old.error);assert.equal(old.error.includes('SECRET'),false);
 const apiCalls=[];let offline=false;
 const v=new V.Vercel({dir:path.join(tmp,'vercel'),now:()=>now,esegui:async args=>{
  apiCalls.push(args);const u=new URL('https://example.test'+args[1]);
  if(offline)return {code:1,stdout:'',stderr:'network error'};
  let body={};
  if(u.pathname==='/v6/deployments') body={deployments:[]};
  if(u.pathname==='/v2/teams') body={teams:[{id:'team_test'}]};
  if(u.pathname==='/v9/projects') body={projects:[raw,{id:'prj_cloud',name:'cloud',accountId:'team_test'}],pagination:{next:null}};
  return {code:0,stdout:JSON.stringify(body),stderr:''};
 }});
 const state=await v.refresh([local]);
 assert.equal(state.catalog.length,2,'catalogo include cloud senza deployment e senza cartella');
 assert.equal(state.catalog.find(p=>p.id==='prj_cloud').state,'NONE');
 assert.ok(apiCalls.some(a=>a[1].includes('teamId=team_test')));
 assert.equal(fs.readFileSync(path.join(tmp,'vercel/vercel.json'),'utf8').includes('NEVER_CACHE'),false);
 now+=9000000;offline=true;
 const previous=await v.refresh([local]);assert.equal(previous.catalog.length,2);assert.equal(previous.catalogAt,state.catalogAt);
 const dom=new JSDOM('<div id="root"></div>',{runScripts:'outside-only',url:'https://example.test'});
 dom.window.eval(fs.readFileSync(path.join(__dirname,'../media/vercel.js'),'utf8'));
 const posted=[];const root=dom.window.document.getElementById('root');
 const room=dom.window.BottegaVercel.mount(root,{post:m=>posted.push(m)});
 room.update({home:tmp,radar:{vercel:state}});
 assert.equal(root.querySelectorAll('.vrc-project').length,2);
 root.querySelector('#vrc-filter').value='cloud';root.querySelector('#vrc-filter').dispatchEvent(new dom.window.Event('change'));
 assert.equal(root.querySelectorAll('.vrc-project').length,1);
 root.querySelector('#vrc-refresh').click();assert.equal(posted[0].type,'vercel.refresh');
 const search=root.querySelector('#vrc-search');search.value='<script>';search.dispatchEvent(new dom.window.Event('input'));
 assert.equal(root.querySelectorAll('.vrc-project').length,0);assert.equal(root.querySelectorAll('script').length,0);
 dom.window.close();
 console.log('Stack Clienti e Vercel: identità, conflitti, ore, paginazione, cache, privacy e interfaccia PASS');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>fs.rmSync(tmp,{recursive:true,force:true}));
